# Change the name of the file to config.ini
# Edit this file to add your personal configuration

[vaults_names]
option_1 = [vault_1] # Do not change the name "option_1"! You can change the vault name. It must match the vault path key (below).
# Other vaults names]

[vaults_paths]
vault_1 = C:\some\vault_name
# Other vaults paths

